### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by venushkadharmasiri** [DrDanL/KinectRecorder#1]
Severity    Code    Description Project File    Line    Suppression State
Error   CS0246  The type or namespace name 'Body' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   126 Active
Error   CS0246  The type or namespace name 'BodyFrameReader' could not be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   141 Active
Error   CS0246  The type or namespace name 'ColorFrameReader' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   161 Active
Error   CS0246  The type or namespace name 'DepthFrameReader' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   166 Active
Error   CS0246  The type or namespace name 'ColorFrameArrivedEventArgs' could not be found (are you missing a using directive or an assembly reference?)    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   404 Active
Error   CS0246  The type or namespace name 'DepthFrameArrivedEventArgs' could not be found (are you missing a using directive or an assembly reference?)    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   522 Active
Error   CS0246  The type or namespace name 'BodyFrameArrivedEventArgs' could not be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   620 Active
Error   CS0246  The type or namespace name 'HandState' could not be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   806 Active
Error   CS0246  The type or namespace name 'Body' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   989 Active
Error   CS0117  'KinectSensor' does not contain a definition for 'GetDefault'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   217 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'Open' and no extension method 'Open' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   224 Active
Error   CS0246  The type or namespace name 'FrameDescription' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   228 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'ColorFrameSource' and no extension method 'ColorFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   228 Active
Error   CS0246  The type or namespace name 'FrameDescription' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   229 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'DepthFrameSource' and no extension method 'DepthFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   229 Active
Error   CS0246  The type or namespace name 'Body' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   230 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'BodyFrameSource' and no extension method 'BodyFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   230 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'ColorFrameSource' and no extension method 'ColorFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   237 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'DepthFrameSource' and no extension method 'DepthFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   238 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'BodyFrameSource' and no extension method 'BodyFrameSource' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   239 Active
Error   CS1061  'KinectSensor' does not contain a definition for 'Close' and no extension method 'Close' accepting a first argument of type 'KinectSensor' could be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   383 Active
Error   CS0246  The type or namespace name 'ColorFrameReference' could not be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   406 Active
Error   CS0246  The type or namespace name 'ColorFrame' could not be found (are you missing a using directive or an assembly reference?)    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   415 Active
Error   CS0246  The type or namespace name 'FrameDescription' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   424 Active
Error   CS0117  'ColorImageFormat' does not contain a definition for 'Bgra' Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   453 Active
Error   CS0117  'ColorImageFormat' does not contain a definition for 'Bgra' Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   459 Active
Error   CS0246  The type or namespace name 'DepthFrameReference' could not be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   524 Active
Error   CS0246  The type or namespace name 'DepthFrame' could not be found (are you missing a using directive or an assembly reference?)    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   528 Active
Error   CS0246  The type or namespace name 'FrameDescription' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   536 Active
Error   CS0246  The type or namespace name 'BodyFrameReference' could not be found (are you missing a using directive or an assembly reference?)    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   622 Active
Error   CS0246  The type or namespace name 'BodyFrame' could not be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   626 Active
Error   CS0246  The type or namespace name 'Body' could not be found (are you missing a using directive or an assembly reference?)  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   646 Active
Error   CS0246  The type or namespace name 'ColorSpacePoint' could not be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   658 Active
Error   CS1061  'CoordinateMapper' does not contain a definition for 'MapCameraPointToColorSpace' and no extension method 'MapCameraPointToColorSpace' accepting a first argument of type 'CoordinateMapper' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   658 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   709 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   710 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   716 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   717 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   724 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   724 Active
Error   CS0117  'JointType' does not contain a definition for 'Neck'    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   744 Active
Error   CS0117  'JointType' does not contain a definition for 'Neck'    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   745 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineShoulder'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   745 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineShoulder'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   746 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineMid'    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   746 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineMid'    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   747 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineBase'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   747 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineShoulder'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   748 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineShoulder'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   749 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineBase'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   750 Active
Error   CS0117  'JointType' does not contain a definition for 'SpineBase'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   751 Active
Error   CS0117  'JointType' does not contain a definition for 'HandTipRight'    Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   757 Active
Error   CS0117  'JointType' does not contain a definition for 'ThumbRight'  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   758 Active
Error   CS0117  'JointType' does not contain a definition for 'HandTipLeft' Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   764 Active
Error   CS0117  'JointType' does not contain a definition for 'ThumbLeft'   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   765 Active
Error   CS0246  The type or namespace name 'TrackingState' could not be found (are you missing a using directive or an assembly reference?) Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   782 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   784 Active
Error   CS0103  The name 'TrackingState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   788 Active
Error   CS0103  The name 'HandState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   810 Active
Error   CS0103  The name 'HandState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   814 Active
Error   CS0103  The name 'HandState' does not exist in the current context  Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   818 Active
Error   CS0246  The type or namespace name 'ColorSpacePoint' could not be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   1003    Active
Error   CS1061  'CoordinateMapper' does not contain a definition for 'MapCameraPointToColorSpace' and no extension method 'MapCameraPointToColorSpace' accepting a first argument of type 'CoordinateMapper' could be found (are you missing a using directive or an assembly reference?)   Kinect-Record   C:\Users\venushka\Desktop\KinectRecorder-master\KinectRecorder-master\RecordKinect\MainWindow.xaml.cs   1003    Active

**Comment by DrDanL** [comment]
This seems to be an issue with the SDK. Which version are you using?

**Comment by venushkadharmasiri** [comment]
v1.8.0 the newest one.

**Comment by DrDanL** [comment]
These errors are related to the version of the SDK you are using. To use the recorder you will have to roll back to an earlier version. I think v1.5. By rolling back the app will work.
